spring.application.name=demo1_jwt
server.port=8085
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=spring_security_demo;encrypt=false;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
logging.level.org.springframework.security=DEBUG
jwt.secret=your-256-bit-secret-key-must-be-at-least-32-characters-long
jwt.expiration=86400000 