spring.application.name=LittleLotus


# --- Cấu hình Database ---
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=WebFashionShop;encrypt=false;
spring.datasource.username=sa
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- Cấu hình JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=update 
spring.jpa.show-sql=true 

# Đặt tên Dialect cho MS SQL Server
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# --- Cấu hình Thymeleaf ---
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false 

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB